### ISSUE TITLE
在处理jar时抛出了ConcurrentModificationException异常

### ISSUE THREAD

**Issue by alfredxl** [HujiangTechnology/gradle_plugin_android_aspectjx#122]
~~~~~~~~~~~~~input file: /data/jenkins/workspace/ta-develop-v3/app/build/intermediates/transforms/com.alibaba.arouter/normal/release/116.jar
~~~~~~~~~~~~~input file: /data/jenkins/workspace/ta-develop-v3/app/build/intermediates/transforms/com.alibaba.arouter/normal/release/117.jar
~~~~~~~~~~~~~input file: /data/jenkins/workspace/ta-develop-v3/app/build/intermediates/transforms/com.alibaba.arouter/normal/release/118.jar
ABORT
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.aspectj.bridge.MessageHandler.hasAnyMessage(MessageHandler.java:160)
	at org.aspectj.weaver.Dump.shouldDumpOnExit(Dump.java:179)
	at org.aspectj.weaver.Dump.dumpOnExit(Dump.java:147)
	at org.aspectj.weaver.Dump.dumpOnExit(Dump.java:135)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:116)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.GeneratedMethodAccessor522.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~~~~~~~~~~~~~~~~~~onFinished

**Comment by firefly1126** [comment]
谢谢反馈，会尽快修复该问题。

**Comment by xybean** [comment]
请问该问题修复了吗，目前2.0.4版本也能复现这个问题。

**Comment by songchuanyang** [comment]
targetSDK=28时编译出现这个问题，退回27时没有问题

**Comment by xuuhaoo** [comment]
请问2018年就说要修的问题...为什么都0202年了..还没修? 
@firefly1126

**Comment by michaelrepo** [comment]
+1

**Comment by puderty** [comment]
aspectjtools并不支持多线程，从1.8.x版本到最新的1.9.7版本都不支持。
看反编译的aspectjtools可以发现，MessageHandler被设置为Dump的static变量，多线程环境下同时多个线程读写。
在1.9.7里ClasspathJar里的openArchives也是static，也存在多线程问题。

这个多线程问题导致了所有未关闭的这个异常以及所有的zip is empty的问题，每个zip is empty都跟exclude没有关系。

BatchTaskScheduler这个类的Executors.newScheduledThreadPool参数直接改成1可以修复这个问题，不过多线程就没了，会慢一些

> 请问2018年就说要修的问题...为什么都0202年了..还没修?
> @firefly1126

**Comment by wurensen** [comment]
> aspectjtools并不支持多线程，从1.8.x版本到最新的1.9.7版本都不支持。
> 看反编译的aspectjtools可以发现，MessageHandler被设置为Dump的static变量，多线程环境下同时多个线程读写。
> 在1.9.7里ClasspathJar里的openArchives也是static，也存在多线程问题。
> 
> 这个多线程问题导致了所有未关闭的这个异常以及所有的zip is empty的问题，每个zip is empty都跟exclude没有关系。
> 
> BatchTaskScheduler这个类的Executors.newScheduledThreadPool参数直接改成1可以修复这个问题，不过多线程就没了，会慢一些
> 
> > 请问2018年就说要修的问题...为什么都0202年了..还没修?
> > @firefly1126

是的，问题本质是aspectjtools不支持多线程运行。
