### ISSUE TITLE
gradle 3.2.1 编译报错

### ISSUE THREAD

**Issue by CodeIdeal** [HujiangTechnology/gradle_plugin_android_aspectjx#132]
编译报错信息：

```gradle
:app:transformClassesWithAjxForDebug
~~~~~~~~~~~~~~~~~~~~~~~ check aspectjx enable
~~~~~~~~~~~~~~~~~~~~cache aspect files
~~~~~~~~~~~~collect aspect file:D:\Personal Project\laboratory\app\build\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\codeideal\laboratory\aspectj\AppAspectJ.class
~~~~~~~~~~~~~~~~~~~~cache input files
~~~~~~~~~~~~~~~~~~~~do aspectj real work
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\org.aspectj\aspectjrt\1.9.2\aa6462d131f63569997e74ecd345359a7d22d1d3\aspectjrt-1.9.2.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\constraint-layout-1.1.3.aar\8281c47a16363ccc12e2e6483132adc3\jars\classes.jar
~~~~~~~~~~~~~input file: D:\Personal Project\laboratory\app\build\intermediates\ajx\debug\includefiles
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\a46ad84f794c7553ac117d427d24c55e\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\recyclerview-v7-27.1.1.aar\8a28292eb45b4c7e0de01a5192dfbf4c\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\support-v4-27.1.1.aar\426215295bbcfd7206232805023e076e\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\cardview-v7-27.1.1.aar\e709154ad5a8465e06b38db1251546f0\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\multidex-1.0.3.aar\fa7a0ee95ba26e8ea900dbe107bd58ee\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\glide\4.1.1\5cf10dddd902443677b1614579f1183f952f3666\glide-4.1.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\okhttp3-integration\4.1.1\97c8b2d2845634612ee09487d8fc7c66c5e5ff41\okhttp3-integration-4.1.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\butterknife-8.8.1.aar\4239d159e1bb9757b72fb0134589160c\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\rxbinding-2.0.0.aar\a4b53ae216ce59a187fcb72554827336\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.squareup.retrofit2\adapter-rxjava2\2.4.0\9286ea8ac29dc3822cca03291259db825e118506\adapter-rxjava2-2.4.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.jakewharton.rxrelay2\rxrelay\2.0.0\2ed3d43181bb62afb00f675d17f3e6c2ffadd889\rxrelay-2.0.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\rxandroid-2.0.2.aar\d5576d4b129cf243e5bf660c6138d00b\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\io.reactivex.rxjava2\rxjava\2.1.9\afd2ab255e6b94b064ea87c2ccd84ac0d163a427\rxjava-2.1.9.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.squareup.retrofit2\converter-scalars\2.4.0\8f4582bcc7c736e0bae775d562074dcdc0c335ad\converter-scalars-2.4.0.jar
java.lang.RuntimeException: Crashed whilst crashing with this exception: java.lang.RuntimeException: Unknown constant type 18
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1718)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1641)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1406)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1159)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
	at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:471)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1051)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:274)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.GeneratedMethodAccessor1703.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unknown constant type 18
	at org.aspectj.apache.bcel.classfile.ConstantPool.constantToString(ConstantPool.java:212)
	at org.aspectj.weaver.bcel.LazyMethodGen$BodyPrinter.printInstruction(LazyMethodGen.java:782)
	at org.aspectj.weaver.bcel.LazyMethodGen$BodyPrinter.print(LazyMethodGen.java:726)
	at org.aspectj.weaver.bcel.LazyMethodGen$BodyPrinter.run(LazyMethodGen.java:652)
	at org.aspectj.weaver.bcel.LazyMethodGen.print(LazyMethodGen.java:613)
	at org.aspectj.weaver.bcel.LazyClassGen.printOne(LazyClassGen.java:860)
	at org.aspectj.weaver.bcel.LazyClassGen.print(LazyClassGen.java:819)
	at org.aspectj.weaver.bcel.LazyClassGen.toLongString(LazyClassGen.java:807)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1716)
	... 28 more
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.squareup.retrofit2\converter-gson\2.4.0\15d7790ee311d961379c51b00aba12d5967cb7ea\converter-gson-2.4.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.squareup.retrofit2\retrofit\2.4.0\fc4aa382632bfaa7be7b41579efba41d5a71ecf3\retrofit-2.4.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\3.10.0\7ef0f1d95bf4c0b3ba30bbae25e0e562b05cf75e\okhttp-3.10.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.squareup.okio\okio\1.15.0\bc28b5a964c8f5721eb58ee3f3c47a9bcbf4f4d8\okio-1.15.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\BaseRecyclerViewAdapterHelper-2.9.42.aar\4d38e727abf6e6d8b9fe192a7c6708a1\jars\classes.jar
trouble in: 
com.codeideal.laboratory.aspectj.AppAspectJ
java.lang.IllegalStateException: there is no classname for invokedynamic
	at org.aspectj.apache.bcel.generic.InvokeDynamic.getClassName(InvokeDynamic.java:126)
	at org.aspectj.weaver.bcel.BcelAccessForInlineMunger.openAroundAdvice(BcelAccessForInlineMunger.java:141)
	at org.aspectj.weaver.bcel.BcelAccessForInlineMunger.munge(BcelAccessForInlineMunger.java:80)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:440)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:100)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1697)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1641)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1406)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1159)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
	at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:471)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1051)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:274)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.GeneratedMethodAccessor1703.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\utilcode-1.9.0.aar\eeca5047498f1b3c060c47fc8cf21a8c\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\logger-2.2.0.aar\dcb26f8ba4f18e57cf4e6095371f460c\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\permission-2.0.0-rc11.aar\5ff2fd5748f6b8566e1f9dc9bed5ff3e\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.readystatesoftware.sqliteasset\sqliteassethelper\2.0.1\d5f02e4a4d65ec0fbb339f2e4228723d1540bb9f\sqliteassethelper-2.0.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\support-media-compat-27.1.1.aar\80f07fb209a8fc8a5e76519646977fba\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\support-fragment-27.1.1.aar\c67f899508bf158e3d204808a222fc63\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\animated-vector-drawable-27.1.1.aar\ed042db0c85743b555596dcbaf9586d4\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\support-core-ui-27.1.1.aar\f7ec123517849a31cbdffaf4305d416e\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\support-core-utils-27.1.1.aar\a6d68e7139e2cea750a5df76c9d33c71\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\support-vector-drawable-27.1.1.aar\936908000395f68e809df263b4b0cd93\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\support-compat-27.1.1.aar\bdcf395b8fe60cc1433c70926b3f5265\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\gifdecoder\4.1.1\df97c1211882e43d08911e0b82eb6e1b25b3d311\gifdecoder-4.1.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife-annotations\8.8.1\bc373fb6bc7bca3035041b924f158fd2b946ee8d\butterknife-annotations-8.8.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.android.support\support-annotations\27.1.1\39ded76b5e1ce1c5b2688e1d25cdc20ecee32007\support-annotations-27.1.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\disklrucache\4.1.1\d02b9bad9380a7f98248e58ec9df65023226259e\disklrucache-4.1.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\annotations\4.1.1\e336eaee0493d7a441c8e7adbaf38d1d78e58596\annotations-4.1.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\org.reactivestreams\reactive-streams\1.0.2\323964c36556eb0e6209f65c1cef72b53b461ab8\reactive-streams-1.0.2.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.google.android\android\4.1.1.4\3fb039385e71e9aa2ba547ea9ea8caa34a4ffac7\android-4.1.1.4.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.2\3edcfe49d2c6053a70a2a47e4e1c2f94998a49cf\gson-2.8.2.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\livedata-core-1.1.0.aar\f94055303b3ffebc2a9845656727a809\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\viewmodel-1.1.0.aar\6a38e50ef4cfd66cc34bc2ab92885d2f\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.1.1\5043bfebc3db072ed80fbd362e7caf00e885d8ae\commons-logging-1.1.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.0.1\1d7d28fa738bdbfe4fbd895d9486308999bdf440\httpclient-4.0.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\org.khronos\opengl-api\gl1.1-android-2.1_r1\8827d279add29cf9115820671e7879de7bf80390\opengl-api-gl1.1-android-2.1_r1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\xerces\xmlParserAPIs\2.6.2\65acede1e5305bd2b92213d7b5761328c6f4fd9\xmlParserAPIs-2.6.2.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\xpp3\xpp3\1.1.4c\9b988ea84b9e4e9f1874e390ce099b8ac12cfff5\xpp3-1.1.4c.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\org.json\json\20080701\d652f102185530c93b66158b1859f35d45687258\json-20080701.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\runtime-1.1.0.aar\f1f9fa3fe0fae9221a6afe8a4efa2e07\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\android.arch.lifecycle\common\1.1.0\edf3f7bfb84a7521d0599efa3b0113a0ee90f85\common-1.1.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\transforms-1\files-1.1\runtime-1.1.0.aar\1e39dfdba046de9c6dddfdd3dcff7dfb\jars\classes.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\android.arch.core\common\1.1.0\8007981f7d7540d89cd18471b8e5dcd2b4f99167\common-1.1.0.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.0.1\e813b8722c387b22e1adccf7914729db09bcb4a9\httpcore-4.0.1.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.3\fd32786786e2adb664d5ecc965da47629dca14ba\commons-codec-1.3.jar
~~~~~~~~~~~~~input file: C:\Users\KY\.gradle\caches\modules-2\files-2.1\com.android.support.constraint\constraint-layout-solver\1.1.3\bde0667d7414c16ed62d3cfe993cff7f9d732373\constraint-layout-solver-1.1.3.jar
~~~~~~~~~~~~~input file: D:\Personal Project\laboratory\devtools\build\intermediates\intermediate-jars\debug\classes.jar
~~~~~~~~~~~~~input file: D:\Personal Project\laboratory\rxbus\build\intermediates\intermediate-jars\debug\classes.jar
~~~~~~~~~~~~~input file: D:\Personal Project\laboratory\rxbus-annotations\build\libs\rxbus-annotations.jar
~~~~~~~~~~~~~~~~~~~~onFinished
putExtensionConfig:D:\Personal Project\laboratory\app\build\intermediates\ajx\extensionconfig.json
{"enabled":true,"ajcArgs":[],"includes":[],"excludes":[]}
:app:transformClassesWithAjxForDebug spend 4210ms
:app:transformClassesWithDexBuilderForDebug
```

**Comment by firefly1126** [comment]
把 第三库 `com.squareup.retrofit2`，`BaseRecyclerViewAdapterHelper ` exclude 掉看看

**Comment by CodeIdeal** [comment]
我直接用了include来限定只有自己的代码会被切入，还是报错。
报错是在升级了gradle版本后出现的，之前都是正常的。感觉是和新版本的gradle不兼容了

environment：
- Android Studio 3.2.1
- gradle version: gradle-4.6-all.zip
- gradle build version: com.android.tools.build:gradle:3.2.1
- compileSdkVersion: 28
- buildToolsVersion: 28.0.3

```gradle
:app:transformClassesWithAjxForDebug
~~~~~~~~~~~~~~~~~~~~~~~ check aspectjx enable
~~~~~~~~~~~~~~~~~~~~cache aspect files
~~~~~~~~~~~~collect aspect file:D:\Personal Project\laboratory\app\build\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\codeideal\laboratory\aspectj\AppAspectJ.class
~~~~~~~~~~~~~~~~~~~~cache input files
~~~~~~~~~~~~~~~~~~~~do aspectj real work
~~~~~~~~~~~~~input file: D:\Personal Project\laboratory\app\build\intermediates\ajx\debug\includefiles
java.lang.RuntimeException: Crashed whilst crashing with this exception: java.lang.RuntimeException: Unknown constant type 18
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1718)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1641)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1406)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1159)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
	at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:471)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1051)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:274)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unknown constant type 18
	at org.aspectj.apache.bcel.classfile.ConstantPool.constantToString(ConstantPool.java:212)
	at org.aspectj.weaver.bcel.LazyMethodGen$BodyPrinter.printInstruction(LazyMethodGen.java:782)
	at org.aspectj.weaver.bcel.LazyMethodGen$BodyPrinter.print(LazyMethodGen.java:726)
	at org.aspectj.weaver.bcel.LazyMethodGen$BodyPrinter.run(LazyMethodGen.java:652)
	at org.aspectj.weaver.bcel.LazyMethodGen.print(LazyMethodGen.java:613)
	at org.aspectj.weaver.bcel.LazyClassGen.printOne(LazyClassGen.java:860)
	at org.aspectj.weaver.bcel.LazyClassGen.print(LazyClassGen.java:819)
	at org.aspectj.weaver.bcel.LazyClassGen.toLongString(LazyClassGen.java:807)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1716)
	... 28 more
trouble in: 
com.codeideal.laboratory.aspectj.AppAspectJ
java.lang.IllegalStateException: there is no classname for invokedynamic
	at org.aspectj.apache.bcel.generic.InvokeDynamic.getClassName(InvokeDynamic.java:126)
	at org.aspectj.weaver.bcel.BcelAccessForInlineMunger.openAroundAdvice(BcelAccessForInlineMunger.java:141)
	at org.aspectj.weaver.bcel.BcelAccessForInlineMunger.munge(BcelAccessForInlineMunger.java:80)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:440)
	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:100)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1697)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1641)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1406)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1159)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
	at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:471)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1051)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:274)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~~~~~~~~~~~~~~~~~~onFinished
putExtensionConfig:D:\Personal Project\laboratory\app\build\intermediates\ajx\extensionconfig.json
{"enabled":true,"ajcArgs":[],"includes":["com.codeideal.laboratory"],"excludes":[]}
:app:transformClassesWithAjxForDebug spend 2458ms
:app:transformClassesWithDexBuilderForDebug
```

**Comment by forgetman** [comment]
这个关闭了? 怎么解决的?

**Comment by crazysniper** [comment]
怎么解决的啊

**Comment by RunningShadow-007** [comment]
是不是用了lambda?
