### ISSUE TITLE
是否能支持一下gradle4.6?

### ISSUE THREAD

**Issue by forgetman** [HujiangTechnology/gradle_plugin_android_aspectjx#137]
现在android studio 3.2 强制要求gradle版本4.6+

**Comment by forgetman** [comment]
2018-11-21 06:20:59.511 7487-7487/aspect.test.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: aspect.test.app, PID: 7487
    java.lang.NoClassDefFoundError: Failed resolution of: Lvaop/DurationAspect;
        at aspect.test.MainActivity.testDuration(MainActivity.java:70)
        at aspect.test.MainActivity.onCreate(MainActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:6664)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "vaop.DurationAspect" on path: DexPathList[[zip file "/data/app/aspect.test.app-1/base.apk"],nativeLibraryDirectories=[/data/app/aspect.test.app-1/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aspect.test.MainActivity.testDuration(MainActivity.java:70) 
        at aspect.test.MainActivity.onCreate(MainActivity.java:38) 
        at android.app.Activity.performCreate(Activity.java:6664) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by FnAndroid** [comment]
大哥,我也遇到这个问题,你有找到解决方法吗?

**Comment by firefly1126** [comment]
4.6是支持的，应该是其他的问题
