### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by dupengyun** [HujiangTechnology/gradle_plugin_android_aspectjx#192]
插件版本 2.0.5 ：
gradle  :4.6
android gradle plugin :  3.2.1

异常：
ABORT
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at org.aspectj.bridge.MessageHandler.hasAnyMessage(MessageHandler.java:160)
        at org.aspectj.weaver.Dump.shouldDumpOnExit(Dump.java:179)
        at org.aspectj.weaver.Dump.dumpOnExit(Dump.java:147)
        at org.aspectj.weaver.Dump.dumpOnExit(Dump.java:135)
        at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:116)
        at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
        at org.aspectj.tools.ajc.Main.run(Main.java:371)
        at sun.reflect.GeneratedMethodAccessor538.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by yj024502** [comment]
同样问题+1

**Comment by 1monicawang** [comment]
同样问题+1

**Comment by yocn** [comment]
同样问题+1

**Comment by xuuhaoo** [comment]
同样问题+1

**Comment by xuuhaoo** [comment]
作者打算修么

**Comment by michaelrepo** [comment]
+1

**Comment by HuJianChong** [comment]
+1
