### ISSUE TITLE
集成后导致leakcanary出错~~~？

### ISSUE THREAD

**Issue by joy-jianqiang** [HujiangTechnology/gradle_plugin_android_aspectjx#200]
2019-08-21 15:41:38.838 6571-6571/com.jinchu.app.vlive E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jinchu.app.vlive, PID: 6571
    java.lang.RuntimeException: Unable to get provider leakcanary.internal.LeakCanaryFileProvider: java.lang.ClassNotFoundException: Didn't find class "leakcanary.internal.LeakCanaryFileProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.jinchu.app.vlive-fIAMKMFdAuccA7tYo6aDuw==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinchu.app.vlive-fIAMKMFdAuccA7tYo6aDuw==/lib/arm, /data/app/com.jinchu.app.vlive-fIAMKMFdAuccA7tYo6aDuw==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6548)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6036)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5942)
        at android.app.ActivityThread.access$1200(ActivityThread.java:201)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6821)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "leakcanary.internal.LeakCanaryFileProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.jinchu.app.vlive-fIAMKMFdAuccA7tYo6aDuw==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinchu.app.vlive-fIAMKMFdAuccA7tYo6aDuw==/lib/arm, /data/app/com.jinchu.app.vlive-fIAMKMFdAuccA7tYo6aDuw==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6532)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6036) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5942) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:201) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6821) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by joy-jianqiang** [comment]
debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.0-beta-2'

**Comment by haohongxian77** [comment]
@HujiangTech the same issue with me ,using aspectjx version 2.0.7,LeakCanary version 2.0-beta-3

**Comment by haohongxian77** [comment]
@joy-jianqiang how to fix the issue , thank u

**Comment by joy-jianqiang** [comment]
> @joy-jianqiang how to fix the issue 
好像也不是这个导致的问题  当时我也升级了room 后来降级了回去了就没问题了~~~

**Comment by FredLiu111** [comment]
exclude com.squareup 可以解决

**Comment by Knight-ZXW** [comment]
遇到一样的问题
把leakcanary排除后就好了
aspectjx {
            exclude 'com.squareup.leakcanary'
        }
