### ISSUE TITLE
建议添加一些Aspect语法错误的提示

### ISSUE THREAD

**Issue by xingxingxiaoyu** [HujiangTechnology/gradle_plugin_android_aspectjx#201]
我是Aspect的初学者，所以就写了如下代码，然后运行报错，

@Aspect
public class ViewOnClickListenerAspectJ {
    public static final String TAG = "ViewOnClick...AspectJ";

    @Before("execution(* android.view.View.OnClickListener.onClick(android.view.View))")
    public void onClickBefore(final JoinPoint joinPoint) {
        View view = (View) joinPoint.getArgs()[0];
        if (view instanceof TextView) {
            TextView textView = (TextView) view;
            Log.e(TAG, "onClickBefore: " + textView.getText());
        }

    }

    @After("execution(* android.view.View.OnClickListener.onClick(android.view.View))")
    public void onClickAfter(final JoinPoint joinPoint) {
        View view = (View) joinPoint.getArgs()[0];
        if (view instanceof TextView) {
            TextView textView = (TextView) view;
            Log.e(TAG, "onClickAfter: " + textView.getText());
        }
        Log.d(TAG, "onClickAfter: ");

    }

    @AfterReturning("execution(* android.view.View.OnClickListener.onClick(android.view.View))")
    public void onClickAfterReturning(final JoinPoint joinPoint) {
        View view = (View) joinPoint.getArgs()[0];
        if (view instanceof TextView) {
            TextView textView = (TextView) view;
            Log.e(TAG, "onClickAfterReturning: " + textView.getText());
        }

    }

    @AfterThrowing("execution(* android.view.View.OnClickListener.onClick(android.view.View))")
    public void onClickAfterThrowing(final JoinPoint joinPoint) {
        View view = (View) joinPoint.getArgs()[0];
        if (view instanceof TextView) {
            TextView textView = (TextView) view;
            Log.e(TAG, "onClickAfterThrowing: " + textView.getText());
        }

    }

    @Around("execution(* android.view.View.OnClickListener.onClick(android.view.View))")
    public void onClickAround(final ProceedingJoinPoint joinPoint) throws Throwable {
        View view = (View) joinPoint.getArgs()[0];
        if (view instanceof TextView) {
            TextView textView = (TextView) view;
            Log.e(TAG, "onClickAround:before " + textView.getText());
            joinPoint.proceed();
            Log.e(TAG, "onClickAround: after" + textView.getText());
        }

    }
}

错误：
Process: com.example.testaspectj, PID: 8014
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.testaspectj/com.example.testaspectj.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.testaspectj.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.testaspectj-1/base.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2236)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.testaspectj.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.testaspectj-1/base.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.testaspectj-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893) 
    	Suppressed: java.lang.NoClassDefFoundError: com.example.testaspectj.MainActivity
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:321)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        		... 14 more
    	Suppressed: java.io.IOException: Zip archive '/data/app/com.example.testaspectj-1/split_lib_slice_1_apk.apk' doesn't contain classes.dex (error msg: Entry not found)
        at dalvik.system.DexFile.openDexFileNative(Native Method)
    		at dalvik.system.DexFile.openDexFile(Dex

我完全不知道咋回事，后来试着接入gradle-android-aspectj-plugin ，才发现这是个很低级的语法错误。。

**Comment by zhuangyfke** [comment]
当@After、@Before、@Around这三个的参数一致的时候就会出现这样的bug
