### ISSUE TITLE
JDK1.8  Stuido 3.5 Cause: zip file is empty

### ISSUE THREAD

**Issue by a615696671** [HujiangTechnology/gradle_plugin_android_aspectjx#205]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:279)
	at com.android.tools.r8.ArchiveClassFileProvider.<init>(:24)
	at com.android.tools.r8.ArchiveClassFileProvider.<init>(:1)
	at com.android.builder.dexing.r8.CachingArchiveClassFileProvider.<init>(CachingArchiveClassFileProvider.java:32)
	at com.android.builder.dexing.r8.ClassFileProviderFactory.createProvider(ClassFileProviderFactory.java:123)
	at com.android.builder.dexing.r8.ClassFileProviderFactory.<init>(ClassFileProviderFactory.java:93)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:369)
	... 99 more

**Comment by liangxiwei** [comment]
我这块找到原因了，因为有些包名字，特别是谷歌的，会带-，所以需要加上类似于下面的属性：
aspectjx {
    exclude 'com.google.firebase','com.google.android'
}

**Comment by vagrant1991** [comment]
@liangxiwei 具体是加在什么位置？

**Comment by vagrant1991** [comment]
找到了，加在app 下面的build.gradle文件
aspectjx {
    exclude 'com.google.firebase', 'com.google.android'
}

**Comment by fenggit** [comment]
> Caused by: java.util.zip.ZipException: zip file is empty
> at java.util.zip.ZipFile.open(Native Method)
> at java.util.zip.ZipFile.(ZipFile.java:225)
> at java.util.zip.ZipFile.(ZipFile.java:279)
> at com.android.tools.r8.ArchiveClassFileProvider.(:24)
> at com.android.tools.r8.ArchiveClassFileProvider.(:1)
> at com.android.builder.dexing.r8.CachingArchiveClassFileProvider.(CachingArchiveClassFileProvider.java:32)
> at com.android.builder.dexing.r8.ClassFileProviderFactory.createProvider(ClassFileProviderFactory.java:123)
> at com.android.builder.dexing.r8.ClassFileProviderFactory.(ClassFileProviderFactory.java:93)
> at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:369)
> ... 99 more

请问解决了吗？怎么解决的？
