### ISSUE TITLE
添加APJX依赖后，添加最新2.8.6的gson依赖编译失败

### ISSUE THREAD

**Issue by hongpp** [HujiangTechnology/gradle_plugin_android_aspectjx#221]
添加apjx框架后，添加gson最新版的依赖编译就会失败，找了好久才发现这个原因，报错说无法读取某个jar文件，很无奈，把gson版本降低一个就可以编译通过了。。

Caused by: com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file D:\visualEventTracking\app\build\intermediates\transforms\ajx\debug\37.jar
	at com.android.builder.dexing.JarClassFileInput.entries(JarClassFileInput.java:64)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:904)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.access$600(DexArchiveBuilderTransform.java:114)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform$DexConversionWorkAction.run(DexArchiveBuilderTransform.java:697)
	... 27 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at com.android.builder.dexing.JarClassFileInput.entries(JarClassFileInput.java:61)

**Comment by hongpp** [comment]
还是zip file is empty的原因，是框架和Google的一些库有冲突，我把所有的Google的库都exclude掉就好了，
aspectjx {
    exclude 'com.google'
}

**Comment by yangpin** [comment]
我也是这么解决的，阿西吧！！！
