### ISSUE TITLE
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'javaCompileProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

### ISSUE THREAD

**Issue by hongpp** [HujiangTechnology/gradle_plugin_android_aspectjx#230]
加入依赖到项目里面，只要app的build.gradle里面添加apply plugin: 'android-aspectjx'

编译就报错啊，

`Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'javaCompileProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:86)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.procedure.AJXProcedure$_closure1$_closure2.doCall(AJXProcedure.groovy:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:186)
	at org.gradle.api.DomainObjectCollection$all$0.call(Unknown Source)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.procedure.AJXProcedure$_closure1.doCall`

**Comment by firefly1126** [comment]
work with 2.0.8
