### ISSUE TITLE
kotlin跟java混合开发报错Caused by: java.lang.ClassNotFoundException: Didn't find class "xxx.Application"

### ISSUE THREAD

**Issue by Ghostbullets** [HujiangTechnology/gradle_plugin_android_aspectjx#250]
apply plugin: 'android-aspectjx'以后，在app项目里创建了一个java的Activity，一个kotlin的Activity，
当一起使用apsectjx时，运行项目会报错Caused by: java.lang.ClassNotFoundException: Didn't find class "xxx.MyApplication"  ；
当注释掉java的Activity里面的apsectjx时，项目可以运行，请问这个有解决办法吗，不能混合开发吗？麻烦看到回复一下，谢谢

**Comment by ruhaly** [comment]
我貌似也是这个
`2020-04-07 15:51:38.662 17726-17726/com.lion.exeed E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lion.exeed, PID: 17726
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/lion/business/account/UserServiceImpl;
        at com.lion.business.exeed.CheryApplication.initService(CheryApplication.kt:38)
        at com.lion.business.exeed.CheryApplication.onCreate(CheryApplication.kt:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lion.business.account.UserServiceImpl" on path: DexPathList[[zip file "/data/app/com.lion.exeed-XGzQfTWe8Hl89pEGT0bfYQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.lion.exeed-XGzQfTWe8Hl89pEGT0bfYQ==/lib/arm, /data/app/com.lion.exeed-XGzQfTWe8Hl89pEGT0bfYQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.lion.business.exeed.CheryApplication.initService(CheryApplication.kt:38) 
        at com.lion.business.exeed.CheryApplication.onCreate(CheryApplication.kt:28) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
`

**Comment by juziw0** [comment]
解决了吗？我也遇到了这个问题

**Comment by wushaohongly** [comment]
同问，现在没发运行

**Comment by Potato-2020** [comment]
同问，一毛一样的问题

**Comment by StephenGiant** [comment]
一样的问题 不过我是注释掉kapt可以运行

**Comment by Potato-2020** [comment]
> 一样的问题 不过我是注释掉kapt可以运行

注释掉kapt后，ARouter不生效了，遇到过吗

**Comment by xiachengcheng** [comment]
> > 一样的问题 不过我是注释掉kapt可以运行
> 
> 注释掉kapt后，ARouter不生效了，遇到过吗

kapt是帮助kotlin解析注释的插件，注释掉了相当于kotlin里面无法解析诸如@wierd一类的注释，会影响Arouter到功能

**Comment by Potato-2020** [comment]
> > > 一样的问题 不过我是注释掉kapt可以运行
> > 
> > 
> > 注释掉kapt后，ARouter不生效了，遇到过吗
> 
> kapt是帮助kotlin解析注释的插件，注释掉了相当于kotlin里面无法解析诸如@wierd一类的注释，会影响Arouter到功能

是这个意思哈，我注释掉kapt狗，替代成annotationProcessor，这是前提，然后报错的。
我怀疑是配置arguments参数那里出了点儿毛病，build.gradle使用的是kotlin android-extension,配这个参数，放弃使用kapt，导致的，不知所措了

**Comment by xiachengcheng** [comment]
> > > > 一样的问题 不过我是注释掉kapt可以运行
> > > 
> > > 
> > > 注释掉kapt后，ARouter不生效了，遇到过吗
> > 
> > 
> > kapt是帮助kotlin解析注释的插件，注释掉了相当于kotlin里面无法解析诸如@wierd一类的注释，会影响Arouter到功能
> 
> 是这个意思哈，我注释掉kapt狗，替代成annotationProcessor，这是前提，然后报错的。
> 我怀疑是配置arguments参数那里出了点儿毛病，build.gradle使用的是kotlin android-extension,配这个参数，放弃使用kapt，导致的，不知所措了

你是直接引入到实际工程了吗，可以先建立一个demo工程来测试吗。我在demo里面测试没问题。
在实际工程遇到其他问题，估计是多个库的冲突，以及实际工程多module结构冲突。
目前也在处理引入工程的各种问题。

**Comment by leviLt** [comment]
大家都遇到了这样的问题，作者知道怎么处理吗？
