### ISSUE TITLE
编译运行错误  java.util.zip.ZipException: zip file is empty

### ISSUE THREAD

**Issue by gao746700783** [HujiangTechnology/gradle_plugin_android_aspectjx#251]
编译运行 报错信息如下:
`
> Task :app:compileReleaseSources
:app:compileReleaseSources spend 0ms
Cannot read debug info for @Aspect to handle formal binding in pointcuts (please compile with 'javac -g' or '<javac debug='true'.../>' in Ant)

> Task :app:transformClassesWithAjxForRelease
:app:transformClassesWithAjxForRelease spend 2654ms
error processing /home/zhefu/workspace/XXX/app/build/intermediates/transforms/ajx/release/118.jar
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:87)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:68)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

> Task :app:transformClassesWithDexBuilderForRelease FAILED
java.lang.RuntimeException: java.lang.RuntimeException: java.util.zip.ZipException: zip file is empty
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:149)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getInitalGraphData(DesugarIncrementalTransformHelper.java:162)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.makeDesugaringGraph(DesugarIncrementalTransformHelper.java:130)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getDependenciesPaths(DesugarIncrementalTransformHelper.java:231)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.getD8DesugaringCacheInfo(DexArchiveBuilderTransform.java:473)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:396)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:106)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: zip file is empty
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:87)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:68)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 4 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.zip.ZipException: zip file is empty

`

**Comment by guokaihua** [comment]
+1

**Comment by lenmoyouziJiangjun** [comment]
+1
plugin  version: 2.0.10
as version: 4.0 beta3

**Comment by luchuangbin** [comment]
+1

**Comment by AwaiTYu** [comment]
+1

**Comment by Gillben** [comment]
+1

**Comment by tjt852** [comment]
+1

**Comment by tjt852** [comment]
Executing tasks: [:demo:assembleDebug] in project /Users/txxx/sample


> Configure project :demo
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :demo:clean
:demo:clean spend 3ms

> Task :demo:preBuild
:demo:preBuild spend 0ms

> Task :library:preBuild UP-TO-DATE
:library:preBuild spend 0ms

> Task :library:preDebugBuild UP-TO-DATE
:library:preDebugBuild spend 0ms

> Task :library:checkDebugManifest
:library:checkDebugManifest spend 20ms

> Task :library:processDebugManifest
:library:processDebugManifest spend 178ms

> Task :demo:preDebugBuild
:demo:preDebugBuild spend 441ms

> Task :library:compileDebugAidl NO-SOURCE
:library:compileDebugAidl spend 13ms

> Task :demo:compileDebugAidl NO-SOURCE
:demo:compileDebugAidl spend 1ms

> Task :library:packageDebugRenderscript NO-SOURCE
:library:packageDebugRenderscript spend 13ms

> Task :demo:compileDebugRenderscript NO-SOURCE
:demo:compileDebugRenderscript spend 21ms

> Task :demo:checkDebugManifest
:demo:checkDebugManifest spend 8ms

> Task :demo:generateDebugBuildConfig
:demo:generateDebugBuildConfig spend 55ms

> Task :demo:prepareLintJar
:demo:prepareLintJar spend 17ms

> Task :demo:generateDebugSources
:demo:generateDebugSources spend 0ms

> Task :library:compileDebugRenderscript NO-SOURCE
:library:compileDebugRenderscript spend 3ms

> Task :library:generateDebugBuildConfig
:library:generateDebugBuildConfig spend 9ms

> Task :library:generateDebugResValues
:library:generateDebugResValues spend 19ms

> Task :library:generateDebugResources
:library:generateDebugResources spend 1ms

> Task :library:packageDebugResources
:library:packageDebugResources spend 5270ms

> Task :library:generateDebugRFile
:library:generateDebugRFile spend 586ms

> Task :library:prepareLintJar
:library:prepareLintJar spend 9ms

> Task :library:generateDebugSources
:library:generateDebugSources spend 1ms

> Task :library:javaPreCompileDebug
:library:javaPreCompileDebug spend 131ms

> Task :library:compileDebugJavaWithJavac
:library:compileDebugJavaWithJavac spend 171ms

> Task :library:bundleLibCompileDebug
:library:bundleLibCompileDebug spend 97ms

> Task :demo:javaPreCompileDebug
:demo:javaPreCompileDebug spend 216ms

> Task :demo:mainApkListPersistenceDebug
:demo:mainApkListPersistenceDebug spend 27ms

> Task :demo:generateDebugResValues
:demo:generateDebugResValues spend 1ms

> Task :demo:generateDebugResources
:demo:generateDebugResources spend 0ms

> Task :demo:mergeDebugResources
:demo:mergeDebugResources spend 2664ms

> Task :demo:createDebugCompatibleScreenManifests
:demo:createDebugCompatibleScreenManifests spend 13ms

> Task :demo:processDebugManifest
:demo:processDebugManifest spend 361ms

> Task :demo:processDebugResources
:demo:processDebugResources spend 1443ms

> Task :demo:compileDebugJavaWithJavac
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:demo:compileDebugJavaWithJavac spend 2595ms

> Task :demo:compileDebugSources
:demo:compileDebugSources spend 0ms

> Task :demo:mergeDebugShaders
:demo:mergeDebugShaders spend 25ms

> Task :demo:compileDebugShaders
:demo:compileDebugShaders spend 23ms

> Task :demo:generateDebugAssets
:demo:generateDebugAssets spend 0ms

> Task :library:mergeDebugShaders
:library:mergeDebugShaders spend 11ms

> Task :library:compileDebugShaders
:library:compileDebugShaders spend 8ms

> Task :library:generateDebugAssets
:library:generateDebugAssets spend 0ms

> Task :library:packageDebugAssets
:library:packageDebugAssets spend 13ms

> Task :demo:mergeDebugAssets
:demo:mergeDebugAssets spend 157ms

> Task :demo:validateSigningDebug
:demo:validateSigningDebug spend 15ms

> Task :demo:signingConfigWriterDebug
:demo:signingConfigWriterDebug spend 92ms

> Task :demo:checkDebugDuplicateClasses
:demo:checkDebugDuplicateClasses spend 148ms

> Task :library:bundleLibRuntimeDebug
:library:bundleLibRuntimeDebug spend 25ms
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 
formal unbound in pointcut 

> Task :demo:transformClassesWithAjxForDebug
:demo:transformClassesWithAjxForDebug spend 4540ms

> Task :demo:transformClassesWithDexBuilderForDebug
com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file /Users/xxxx/sample/demo/build/intermediates/transforms/ajx/debug/47.jar
	at com.android.builder.dexing.JarClassFileInput.entries(JarClassFileInput.java:64)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:903)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.android.builder.dexing.JarClassFileInput.entries(JarClassFileInput.java:61)
	... 7 more

:demo:transformClassesWithDexBuilderForDebug spend 40451ms

> Task :demo:transformClassesWithDexBuilderForDebug FAILED
      00:40.45   :demo:transformClassesWithDexBuilderForDebug
      00:05.27   :library:packageDebugResources
      00:04.54   :demo:transformClassesWithAjxForDebug
      00:02.66   :demo:mergeDebugResources
      00:02.59   :demo:compileDebugJavaWithJavac
      00:01.44   :demo:processDebugResources
      00:00.58   :library:generateDebugRFile
      00:00.44   :demo:preDebugBuild
      00:00.36   :demo:processDebugManifest
      00:00.21   :demo:javaPreCompileDebug
      00:00.17   :library:processDebugManifest
      00:00.17   :library:compileDebugJavaWithJavac
      00:00.15   :demo:mergeDebugAssets
      00:00.14   :demo:checkDebugDuplicateClasses
      00:00.13   :library:javaPreCompileDebug
      00:00.09   :library:bundleLibCompileDebug
      00:00.09   :demo:signingConfigWriterDebug
      00:00.05   :demo:generateDebugBuildConfig

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':demo:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file /Users/xxxxx/sample/demo/build/intermediates/transforms/ajx/debug/47.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s
35 actionable tasks: 35 executed

**Comment by Wocus** [comment]
没有解决冲突而引起的，看我文章，https://www.jianshu.com/p/3b94562347ef

**Comment by flyou** [comment]
> 没有解决冲突而引起的，看我文章，https://www.jianshu.com/p/3b94562347ef
没什么用

**Comment by EvanEvil** [comment]
> > 没有解决冲突而引起的，看我文章，https://www.jianshu.com/p/3b94562347ef
> > 没什么用

加了还是不行哇

**Comment by EvanEvil** [comment]
> > > 没有解决冲突而引起的，看我文章，https://www.jianshu.com/p/3b94562347ef
> > > 没什么用
> 
> 加了还是不行哇
可以了，我写错了：@Around("process")  方法没有写()

**Comment by study1990** [comment]
aspectjx中exclude添加'kotlin'，kotlin项目就不报zip file is empty错了
