### ISSUE TITLE
Invalid byte tag in constant pool: 19

### ISSUE THREAD

**Issue by somebodyLi** [HujiangTechnology/gradle_plugin_android_aspectjx#254]
`org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:139)
	at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:98)
	at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)
	at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
	at org.aspectj.weaver.bcel.Utility.makeJavaClass(Utility.java:472)
	at org.aspectj.weaver.bcel.UnwovenClassFile.getJavaClass(UnwovenClassFile.java:68)
	at org.aspectj.weaver.bcel.BcelWeaver.addClassFile(BcelWeaver.java:453)
	at org.aspectj.weaver.bcel.BcelWeaver.addJarFile(BcelWeaver.java:400)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:900)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:251)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ABORT`

**Comment by xiachengcheng** [comment]
Same here. Any solution? @firefly1126

**Comment by xiachengcheng** [comment]
测试发现应该是包冲突，我的情况是引入alibaba的arouter导致的。
通过
aspectJ {
  include 'com.my.package'
}
解决的

**Comment by gao746700783** [comment]
我这边通过升级 aspectj 版本最新 解决问题

// aspectj
implementation 'org.aspectj:aspectjrt:1.9.6'
