### ISSUE TITLE
BuildListener#buildStarted(Gradle) has been deprecated. This is scheduled to be removed in Gradle 7.0

### ISSUE THREAD

**Issue by jrjohn** [HujiangTechnology/gradle_plugin_android_aspectjx#266]
> Configure project :app
BuildListener#buildStarted(Gradle) has been deprecated. This is scheduled to be removed in Gradle 7.0.
	at org.gradle.invocation.DefaultGradle.nagBuildStartedDeprecationIfOverriden(DefaultGradle.java:404)
	at org.gradle.invocation.DefaultGradle.addListener(DefaultGradle.java:370)
	at org.gradle.api.invocation.Gradle$addListener$0.call(Unknown Source)
	at com.hujiang.gradle.plugin.android.aspectjx.AJXPlugin.apply(AJXPlugin.groovy:54)
	at com.hujiang.gradle.plugin.android.aspectjx.AJXPlugin.apply(AJXPlugin.groovy)

**Comment by LanderlYoung** [comment]
maybe remove this line 

```java
            project.gradle.addListener(new TimeTrace())

```

Android Studio now has a built-in build time analyzer.
