### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.leakcanary.core.R$bool"

### ISSUE THREAD

**Issue by CMzhizhe** [HujiangTechnology/gradle_plugin_android_aspectjx#293]
######版本说明######
1、 api 'org.aspectj:aspectjrt:1.9.5'
       debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.3'
2、classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.8'
3、classpath 'com.android.tools.build:gradle:3.3.1'
4、apply plugin: 'com.hujiang.android-aspectjx'

######崩溃信息######
```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/leakcanary/core/R$bool;
        at leakcanary.internal.InternalLeakCanary.addDynamicShortcut(InternalLeakCanary.kt:216)
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:148)
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:39)
        at leakcanary.internal.InternalAppWatcher.install(InternalAppWatcher.kt:75)
        at leakcanary.internal.AppWatcherInstaller.onCreate(AppWatcherInstaller.kt:35)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2154)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2128)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7306)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6777)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6627)
        at android.app.ActivityThread.access$1600(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:7709)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.leakcanary.core.R$bool" on path: DexPathList[[zip file "/data/app/com.wjxls.mall-ywQsxfRtxLf1KGovHMfFGQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.wjxls.mall-ywQsxfRtxLf1KGovHMfFGQ==/lib/arm, /data/app/com.wjxls.mall-ywQsxfRtxLf1KGovHMfFGQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at leakcanary.internal.InternalLeakCanary.addDynamicShortcut(InternalLeakCanary.kt:216) 
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:148) 
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:39) 
        at leakcanary.internal.InternalAppWatcher.install(InternalAppWatcher.kt:75) 
        at leakcanary.internal.AppWatcherInstaller.onCreate(AppWatcherInstaller.kt:35) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2154) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2128) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7306) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6777) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6627) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:236) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:7709) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

######采用过的解决方案######
```
aspectjx {
    exclude 'com.squareup.**'
}
```

```
aspectjx {
    exclude 'com.squareup'
}
```

```
aspectjx {
    exclude 'com.squareup.leakcanary'
}
```

```
aspectjx {
    exclude  "android.support",'androidx','com.google','com.squareup.leakcanary','com.squareup.leakcanary.core','com.alipay','org.apache','com.tencent'
}

```
都失败，都是一样的错误。想不到怎么来解决了

**Comment by RunningShadow-007** [comment]
我也遇到同样的问题

**Comment by ChawLoo** [comment]
@RunningShadow-007 @CMzhizhe 
用下面这个
```gradle
aspectjx {
    exclude 'com.squareup'
    exclude 'leakcanary'
}
```
Duplicate of #https://github.com/square/leakcanary/issues/1767
