### ISSUE TITLE
ABORT org.aspectj.weaver.BCException

### ISSUE THREAD

**Issue by zero92723** [HujiangTechnology/gradle_plugin_android_aspectjx#314]
ABORT
org.aspectj.weaver.BCException: Whilst processing type 'Lcom/alipay/apmobilesecuritysdk/common/RushTimeUtil$1;' - cannot cast the outer type to a reference type.  Signature=Lcom/alipay/apmobilesecuritysdk/common/RushTimeUtil; toString()=com.alipay.apmobilesecuritysdk.common.RushTimeUtil class=RushTimeUtil
when processing type mungers 
when weaving 
when batch building with classpath: C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\ajx\debug\includefiles;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\ajx\debug\excludefiles;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\0.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\1.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\2.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\3.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\4.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\5.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\6.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\7.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\8.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\9.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\10.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\11.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\12.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\13.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\14.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\15.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\16.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\17.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\18.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\19.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\20.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\21.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\22.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\23.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\24.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\25.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\26.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\27.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\28.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\29.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\30.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\31.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\32.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\33.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\34.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\35.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\36.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\37.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\38.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\39.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\40.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\41.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\42.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\43.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\44.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\45.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\46.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\47.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\48.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\49.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\50.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\51.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\52.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\53.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\54.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\55.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\56.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\57.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\58.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\59.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\60.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\61.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\62.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\63.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\64.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\65.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\66.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\67.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\68.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\69.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\70.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\71.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\72.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\73.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\74.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\75.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\76.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\77.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\78.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\79.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\80.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\81.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\82.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\83.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\84.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\85.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\86.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\87.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\88.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\89.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\90.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\91.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\92.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\93.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\94.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\95.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\96.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\97.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\98.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\99.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\100.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\101.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\102.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\103.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\104.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\105.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\106.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\107.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\108.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\109.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\110.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\111.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\112.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\113.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\114.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\115.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\116.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\117.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\118.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\119.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\120.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\121.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\122.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\123.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\124.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\125.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\126.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\127.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\128.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\129.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\130.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\131.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\132.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\133.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\134.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\135.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\136.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\137.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\138.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\139.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\140.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\141.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\142.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\143.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\144.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\145.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\146.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\147.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\148.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\149.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\150.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\151.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\152.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\153.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\154.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\155.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\156.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\157.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\158.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\159.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\160.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\161.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\162.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\163.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\164.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\165.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\166.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\167.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\168.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\169.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\170.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\171.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\172.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\173.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\174.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\175.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\176.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\177.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\178.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\179.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\180.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\181.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\182.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\183.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\184.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\185.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\186.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\187.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\188.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\189.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\193.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\194.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\195.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\196.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\197.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\198.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\199.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\200.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\201.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\202.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\203.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\204.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\205.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\206.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\207.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\208.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\209.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\210.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\211.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\212.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\213.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\214.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\215.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\216.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\217.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\218.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\219.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\220.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\221.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\222.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\223.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\224.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\225.jar;F:\Android_Work_Speace\StarsChina9.0_log\app\build\intermediates\transforms\appJoint\debug\226.jar;

	at org.aspectj.weaver.AbstractReferenceTypeDelegate.getFormalTypeParametersFromOuterClass(AbstractReferenceTypeDelegate.java:113)
	at org.aspectj.weaver.bcel.BcelObjectType.ensureGenericSignatureUnpacked(BcelObjectType.java:775)
	at org.aspectj.weaver.bcel.BcelObjectType.getSuperclass(BcelObjectType.java:231)
	at org.aspectj.weaver.ReferenceType.getSuperclass(ReferenceType.java:987)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveParentsFor(BcelWeaver.java:1304)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1123)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
	at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:471)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1051)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:274)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at sun.reflect.GeneratedMethodAccessor1188.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zero92723** [comment]
编译时报错 com.android.tools.build:gradle:3.5.1

**Comment by huzhicheng1993** [comment]
目前我这边的解决方案是 exclude  RushTimeUtil 这种方式
