### ISSUE TITLE
kotlin 中使用 运行报错

### ISSUE THREAD

**Issue by dean-lwh** [HujiangTechnology/gradle_plugin_android_aspectjx#323]
ClassNotFoundException: Didn't find class "com.dean.browser.BaseApplication" on path: DexPathList[[zip file "/data/app/com.dean.browser-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dean.browser-1/lib/x86, /data/app/com.dean.browser-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5411) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6153) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 

配置如下：
buildscript {
    ext.kotlin_version = "1.3.72"
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

module中配置：
apply plugin: 'android-aspectjx'
compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
      targetCompatibility JavaVersion.VERSION_1_8
  }
implementation 'org.aspectj:aspectjrt:1.9.6'

**Comment by XJAlive** [comment]
> ClassNotFoundException: Didn't find class "com.dean.browser.BaseApplication" on path: DexPathList[[zip file "/data/app/com.dean.browser-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dean.browser-1/lib/x86, /data/app/com.dean.browser-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
> at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> at android.app.Instrumentation.newApplication(Instrumentation.java:992)
> at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5411) 
> at android.app.ActivityThread.-wrap2(ActivityThread.java) 
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) 
> at android.os.Handler.dispatchMessage(Handler.java:102) 
> at android.os.Looper.loop(Looper.java:154) 
> at android.app.ActivityThread.main(ActivityThread.java:6153) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
> 
> 配置如下：
> buildscript {
> ext.kotlin_version = "1.3.72"
> repositories {
> google()
> jcenter()
> }
> dependencies {
> classpath 'com.android.tools.build:gradle:3.5.2'
> classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.8'
> // NOTE: Do not place your application dependencies here; they belong
> // in the individual module build.gradle files
> }
> }
> 
> module中配置：
> apply plugin: 'android-aspectjx'
> compileOptions {
> sourceCompatibility JavaVersion.VERSION_1_8
> targetCompatibility JavaVersion.VERSION_1_8
> }
> implementation 'org.aspectj:aspectjrt:1.9.6'

请问你的问题解决了吗，正在被相同问题困扰

**Comment by zhuangxujun** [comment]
同样的问题....
