### ISSUE TITLE
Could not get this feature:is_support_double_system, value is null

### ISSUE THREAD

**Issue by songjian931798** [HujiangTechnology/gradle_plugin_android_aspectjx#33]
05-07 14:59:31.935 16135-16135/com.example.lenovo.androidaop W/FeatureConfig:  Could not get this feature:is_support_double_system, value is null
                                                                              java.lang.Throwable
                                                                                  at com.yulong.android.feature.FeatureConfig.getIntValue(FeatureConfig.java:470)
                                                                                  at com.yulong.android.server.systeminterface.SystemInterfaceImpl.isSupportDoubleOS(SystemInterfaceImpl.java:5295)
                                                                                  at com.yulong.android.server.systeminterface.SystemInterfaceImpl.<clinit>(SystemInterfaceImpl.java:5678)
                                                                                  at java.lang.Class.classForName(Native Method)
                                                                                  at java.lang.Class.forName(Class.java:251)
                                                                                  at java.lang.Class.forName(Class.java:216)
                                                                                  at com.yulong.android.reflect.YLReflect.Load_class(YLReflect.java:59)
                                                                                  at com.yulong.android.reflect.YLReflect.<clinit>(YLReflect.java:40)
                                                                                  at android.app.ContextImpl$49.createService(ContextImpl.java:683)
                                                                                  at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:281)
                                                                                  at android.app.ContextImpl.getSystemService(ContextImpl.java:1760)
                                                                                  at android.media.AudioManager.<init>(AudioManager.java:454)
                                                                                  at android.app.ContextImpl$7.createService(ContextImpl.java:368)
                                                                                  at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:281)
                                                                                  at android.app.ContextImpl.getSystemService(ContextImpl.java:1760)
                                                                                  at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:117)
                                                                                  at android.app.Activity.getSystemService(Activity.java:4590)
                                                                                  at android.view.ViewRootImpl.getAudioManager(ViewRootImpl.java:5570)
                                                                                  at android.view.ViewRootImpl.playSoundEffect(ViewRootImpl.java:5658)
                                                                                  at android.view.View.playSoundEffect(View.java:17276)
                                                                                  at android.view.View.performClick(View.java:4462)
                                                                                  at android.view.View$PerformClick.run(View.java:18772)
                                                                                  at android.os.Handler.handleCallback(Handler.java:808)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                  at android.os.Looper.loop(Looper.java:193)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5367)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by firefly1126** [comment]
这玩意儿好像跟`aspectjx`没有关系。
