### ISSUE TITLE
java.lang.RuntimeException: Unexpected scopes found in folder

### ISSUE THREAD

**Issue by lengxuegang** [HujiangTechnology/gradle_plugin_android_aspectjx#45]
Under android studio 3.0 & gradle 4.1 milestone, I encountered the compile error:

`Caused by: java.lang.RuntimeException: Unexpected scopes found in folder '/app/build/intermediates/transforms/AspectTransform/debug'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS
        at com.android.build.gradle.internal.pipeline.IntermediateFolderUtils.makeRestrictedCopies(IntermediateFolderUtils.java:455)
        at com.android.build.gradle.internal.pipeline.IntermediateFolderUtils.<init>(IntermediateFolderUtils.java:66)
        at com.android.build.gradle.internal.pipeline.IntermediateStream.init(IntermediateStream.java:191)
        at com.android.build.gradle.internal.pipeline.IntermediateStream.asNonIncrementalInput(IntermediateStream.java:146)
        at com.android.build.gradle.internal.pipeline.TransformTask.computeNonIncTransformInput(TransformTask.java:281)
        at com.android.build.gradle.internal.pipeline.TransformTask.access$500(TransformTask.java:70)
        at com.android.build.gradle.internal.pipeline.TransformTask$1.call(TransformTask.java:196)
        at com.android.build.gradle.internal.pipeline.TransformTask$1.call(TransformTask.java:157)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:152)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:168)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)`

I checked the build output dir, and there is a exactly a AspectTransform directory. maybe gradle considers it invalid?

I'm also working with hugo, and knows that our plugin works the same as hugo in the AspectJ part, so i made a compartion of source code between them.

the Hugo plugin is as follows:
`JavaCompile javaCompile = variant.javaCompile
      javaCompile.doLast {
        String[] args = [
            "-showWeaveInfo",
            "-1.5",
            "-inpath", javaCompile.destinationDir.toString(),
            "-aspectpath", javaCompile.classpath.asPath,
            "-d", javaCompile.destinationDir.toString(),
            "-classpath", javaCompile.classpath.asPath,
            "-bootclasspath", project.android.bootClasspath.join(File.pathSeparator)
        ]
        log.debug "ajc args: " + Arrays.toString(args)
        ......`
and our plugin:
`def args = [
                "-showWeaveInfo",
                "-encoding", encoding,
                "-source", sourceCompatibility,
                "-target", targetCompatibility,
                "-d", destinationDir,
                "-classpath", classPath.join(File.pathSeparator),
                "-bootclasspath", bootClassPath
        ]

        if (!getInPath().isEmpty()) {
            args << '-inpath'
            args << getInPath().join(File.pathSeparator)
        }
        if (!getAspectPath().isEmpty()) {
            args << '-aspectpath'
            args << getAspectPath().join(File.pathSeparator)
        }`

i doubt that the output dir differs, which caused gradle report this exception.

**Comment by baoxiehao** [comment]
I came across the same problem.

**Comment by Object-Ping** [comment]
I came across the same problem.

**Comment by Object-Ping** [comment]
I came across the same problem.

**Comment by Tim1008** [comment]
same problem in android studio

**Comment by fatCat2015** [comment]
I came across the same problem. as gradle 4.1,gradle plugin 3.0

**Comment by vicctor** [comment]
Does anyone found solution for this?

**Comment by Hommilist** [comment]
I came across the same problem.

**Comment by ditclear** [comment]
using JAR from product. Make new directory named as plugins, and put product/gradle-android-plugin-aspectjx-1.1.1.jar in plugins, then do as below:

dependencies {
        classpath fileTree(dir:'plugins', include:['*.jar'])
        //don't lost dependency
        classpath 'org.aspectj:aspectjtools:1.8.+'
        }

**Comment by lofei117** [comment]
@ditclear I did by following your step, but still doesn't work.

**Comment by arpitchoudhary** [comment]
I found a solution which works in my case.
I deleted the .gradle and .idle folder from the studio and then re-run the app.
it works fine for me

**Comment by itsymbal** [comment]
arpitchoudhary's suggested solution works for me

**Comment by Deemonser** [comment]
yes, arpitchoudhary's suggested solution works for me

**Comment by Nullifier1571** [comment]
try to close instant run

**Comment by ameerhamza6733** [comment]
try to close instant run or **just unpluge your device from PC** this is automatically stop instant run or turn of your virtual device

**Comment by AXwjg** [comment]
The way I handle it is to uncheck all the contents in Instant Run in Android Studio Settings.

**Comment by naimishvinchhi** [comment]
Clean and run works for me.

**Comment by sinameraji** [comment]
I just clicked "build" project and it fixed the issue

**Comment by staticvoidjames** [comment]
> try to close instant run

that works for me

**Comment by QinHanSoft** [comment]
I tried as arpitchoudhary suggested, and it works for me.
