### ISSUE TITLE
Android Studio 3.0 build failed

### ISSUE THREAD

**Issue by sungerk** [HujiangTechnology/gradle_plugin_android_aspectjx#64]
Error:Execution failed for task ':app:transformClassesWithExtractJarsForDebug'.
> Unexpected scopes found in folder 'C:\Users\Administrator\AndroidStudioProjects\Test\app\build\intermediates\transforms\AspectTransform\debug'. Required: SUB_PROJECTS. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

**Comment by shenqinwei** [comment]
同上

**Comment by gunC** [comment]
我试了下,1.1.0 还没修复..

**Comment by gunC** [comment]
修正一下, 1.1.0是修复了,不过忘记关 instant Run 也是会提示.
你这个应该是忘记关 instant Run .

**Comment by sungerk** [comment]
java 8 not support

**Comment by tzutalin** [comment]
Why should we need to turn off 'instant Run'?

**Comment by YuTianTina** [comment]
still build failed when I turn off instant Run

**Comment by firefly1126** [comment]
最近release的`1.1.1`版本解决了Java8的支持问题，但是这个版本如果用Java8编译，`includeJarFiter`, `excludeJarFilter`这两个过滤配置失效，配置问题会在下个版本修复。

**Comment by sungerk** [comment]
Error:Execution failed for task ':app:transformClassesWithAspectTransformForDebug'.
> org/aspectj/bridge/MessageHandler

换成1.1.1直接就编译不通过了。1.1.0可以

**Comment by wangzhzh** [comment]
换成1.1.1:
java.lang.ClassCastException: org.aspectj.apache.bcel.classfile.ConstantClass cannot be cast to org.aspectj.apache.bcel.classfile.ConstantUtf8
        at org.aspectj.apache.bcel.classfile.ConstantPool.getConstantUtf8(ConstantPool.java:276)
        at org.aspectj.weaver.bcel.BcelConstantPoolReader.readUtf8(BcelConstantPoolReader.java:31)
        at org.aspectj.weaver.VersionedDataInputStream.readUtf8(VersionedDataInputStream.java:61)
        at org.aspectj.weaver.ResolvedMemberImpl.readResolvedMember(ResolvedMemberImpl.java:523)
        at org.aspectj.weaver.AjAttribute$EffectiveSignatureAttribute.read(AjAttribute.java:734)
        at org.aspectj.weaver.AjAttribute.read(AjAttribute.java:127)
        at org.aspectj.weaver.bcel.Utility.readAjAttributes(Utility.java:101)
        at org.aspectj.weaver.bcel.BcelMethod.unpackAjAttributes(BcelMethod.java:198)
        at org.aspectj.weaver.bcel.BcelMethod.<init>(BcelMethod.java:91)
        at org.aspectj.weaver.bcel.BcelObjectType.getDeclaredMethods(BcelObjectType.java:291)
        at org.aspectj.weaver.ReferenceType.getDeclaredMethods(ReferenceType.java:864)
        at org.aspectj.weaver.ResolvedType.getDeclaredAdvice(ResolvedType.java:977)
        at org.aspectj.weaver.ResolvedType.getDeclaredShadowMungers(ResolvedType.java:1017)
        at org.aspectj.weaver.ResolvedType.collectShadowMungers(ResolvedType.java:843)
        at org.aspectj.weaver.ResolvedType.collectCrosscuttingMembers(ResolvedType.java:770)
        at org.aspectj.weaver.CrosscuttingMembersSet.addOrReplaceAspect(CrosscuttingMembersSet.java:113)
        at org.aspectj.weaver.CrosscuttingMembersSet.addOrReplaceAspect(CrosscuttingMembersSet.java:68)
        at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:239)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:874)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:249)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:185)
        at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
        at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
        at org.aspectj.tools.ajc.Main.run(Main.java:371)

**Comment by lizhifeng-sky** [comment]
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> Unexpected scopes found in folder 'D:\lizhifeng\aspect\app\build\intermediates\transforms\AspectTransform\debug'. Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

**Comment by lizhifeng-sky** [comment]
gradle 4.3.1

**Comment by meablelee2013** [comment]
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> Unexpected scopes found in folder 
 Required: PROJECT, SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, PROJECT_LOCAL_DEPS, SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS

gradle-4.1-all.zip

whether turn off instant run on or off ,it`s not work

**Comment by kirtan403** [comment]
Same problem for me too. Any way to get around this to make this work?

**Comment by firefly1126** [comment]
2.0.0做了重大调整，有更好的编译效率和稳定性，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`

**Comment by wangkunlin** [comment]
@firefly1126 请教一下, 这个问题怎么解得？我也自定义插件也遇到了这个问题  Required: SUB_PROJECTS. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS .

**Comment by xckevin** [comment]
同问怎么修改的，就是把getScope改成ALL_PROJECT吗？
