### ISSUE TITLE
Abort building for the first time

### ISSUE THREAD

**Issue by tzutalin** [HujiangTechnology/gradle_plugin_android_aspectjx#68]
commands: ./gradlew clean;./gradlew assembleDebug 
Version: 1.1.0

````
ABORT
java.util.EmptyStackException
```
org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
:RobotVisionService:transformClassesWithAspectTransformForxxxxDebug FAILED
:RobotVisionService:transformClassesWithAspectTransformForxxxxDebug spend 782ms
:RobotVisionService:transformClassesWithAspectTransformForxxxxDebug spend 782ms
aspect jar merging..........
cannot find QualifiedContent.Scope.PROJECT_LOCAL_DEPS Deprecated.class 
```

**Comment by firefly1126** [comment]
Tell me gradle version and android plugin version your project build with

**Comment by firefly1126** [comment]
2.0.0做了重大调整，可以尝试一下2.0.0版本，该版本做了如下调整：
* 支持Instant Run编译
* 废弃 includeJarFilter和excludeJarFilter两个配置命令
* 新增 include和 exclude配置命令，通过包名(package)路径关键字匹配，可过滤class文件和库文件(jar)
* include和 exclude配置命令支持*，**通配符
* 修复已知的gradle兼容性Bug
* 提升编译效率
* 解决 `Could not find matching constructor for: org.gradle.util.Clock()`
