### ISSUE TITLE
java.lang.NoSuchMethodError: No static method aspectOf()

### ISSUE THREAD

**Issue by evanyu1024** [HujiangTechnology/gradle_plugin_android_aspectjx#92]
不添加过滤配置时，插件能够正常使用，但是添加过滤配置后，出现了 java.lang.NoSuchMethodError: No static method aspectOf() 错误

具体信息如下：

插件版本：2.0.1
在demo中接入测试，打的是debug包，没有任何混淆和加固

// 添加了如下过滤配置
aspectjx {
        include 'com.maizijf.analytics'
}
// 具体报错信息：
java.lang.NoSuchMethodError: No static method aspectOf()Lcom/maizijf/maizilib/demo/analytics/AspectjAnalyticsManager; in class Lcom/maizijf/maizilib/demo/analytics/AspectjAnalyticsManager; or its super classes (declaration of 'com.maizijf.maizilib.demo.analytics.AspectjAnalyticsManager' appears in /data/app/com.maizijf.maizilib-3u5oRYhgm_qiVXHmK81jQA==/base.apk:classes20.dex)
        at com.maizijf.analytics.manager.debugtool.DebugViewManager$2.onClick(DebugViewManager.java:153)
        at android.view.View.performClick(View.java:6877)
        at android.widget.TextView.performClick(TextView.java:12651)
        at com.maizijf.analytics.manager.debugtool.DraggableFloatingButton.onTouchEvent(DraggableFloatingButton.java:92)
        at android.view.View.dispatchTouchEvent(View.java:12520)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5615)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5410)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4903)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4956)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4922)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5059)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4930)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5116)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4903)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4956)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4922)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4930)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4903)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7654)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7594)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7555)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7765)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by dcjniwota** [comment]
遇到同样的问题，请问如何解决呢？

**Comment by ban54** [comment]
遇到相同的问题了，有没有解决方案？

**Comment by Zhoucj1986** [comment]
我也遇到这个问题了，用楼上的方法不好使，因为我的过滤包名和aop代码包名本身就是一样的

**Comment by OnlyMyRailgun** [comment]
我也遇到了…

**Comment by SilenceControl** [comment]
同样遇到，大家有解决的嘛？求解决方案啊，，，

**Comment by OnlyMyRailgun** [comment]
用 @ban54 的方法我这边解决了

**Comment by qsmaxmin** [comment]
include标签不管怎么设置，貌似只能让当前项目生效，如果你的框架里有AOP代码，就不能用include标签。
所以建议还是回退到1.1.1版本吧，用includeJarFilter标签把你需要的项目加进来

**Comment by firefly1126** [comment]
`include`和`exclude`的规则是去匹配包名，如果找到匹配的包名，则整个jar(即整个库)生效，这样做主要是考虑到性能的问题。`include`和`exclude`在功能上是没有问题的。

**Comment by CodingZh** [comment]
> 我也遇到这个问题了，用楼上的方法不好使，因为我的过滤包名和aop代码包名本身就是一样的
> 还有，aop代码本身是作为一个module，而被切面的代码是主工程

我也想这么做,发现遇到同样的问题,请问你最后怎么解决的?

**Comment by carl1990** [comment]
我遇见了同样的问题
用 @ban54  的方法我这边解决了  👍

**Comment by ZhangQixiangChina** [comment]
> 我也遇到这个问题了，用楼上的方法不好使，因为我的过滤包名和aop代码包名本身就是一样的
> 还有，aop代码本身是作为一个module，而被切面的代码是主工程

需要把
```
apply plugin: 'android-aspectjx'

aspectjx {
    include 'xxxx'
}
```
这部分写在app的build.gradle中而不是你aspect代码所在的module中

**Comment by RibsStorm** [comment]
用  @ban54 的方法,解决问题.多谢!

**Comment by lacker159** [comment]
感谢 @ZhangQixiangChina 老哥, 解决问题, 多谢!
问题原因: 在 app 和 module 的 build.gradle 都配置 aspectjx
解决方案: 把 aspectjx 配置从 module  移动到 app 中

**Comment by gudujiucheng** [comment]
如果是利用这个封装jar或者aar然后同时用include 和 exclude 就容易掉坑，因为不配置include就无法插桩，但是有些场景同个jar又需要配置exclude防止替换类二次被插桩导致死循环，这种情况就满足不了，只能把配置类和实现类分成两个jar才好规避这个问题

对应方法：AJXUtils.filterJar，相关判断代码

```
JarFile jarFile = new JarFile(jarInput.file)
            Enumeration<JarEntry> entries = jarFile.entries()
            while (entries.hasMoreElements()) {
                JarEntry jarEntry = entries.nextElement()
                String entryName = jarEntry.getName()
                String tranEntryName = entryName.replace("/", ".").replace("\\", ".")
                if (isIncludeFilterMatched(tranEntryName, includes)) {//FIXME 如果同一个jar 包含和不包含的条件同时满足，会出现问题
                    isIncludeMatched = true
                }

                if (isExcludeFilterMatched(tranEntryName, excludes)) {
                    isExcludeMatched = true
                }
            }

            jarFile.close()

            if (isIncludeMatched && !isExcludeMatched) {//FIXME  就是这里，同一个jar包 不能同时include和exclude
                //put in cache
                variantCache.addIncludeJar(jarInput.file.absolutePath)
            }
```
