### ISSUE TITLE
2.0.1版本空项目崩溃

### ISSUE THREAD

**Issue by r17171709** [HujiangTechnology/gradle_plugin_android_aspectjx#93]
新建一个空项目，按照说明进行配置，2.0.0版本直接运行没问题，2.0.1版本报错
`java.lang.NoClassDefFoundError: android.support.v7.appcompat.R$drawable
        at android.support.v7.widget.AppCompatDrawableManager.<clinit>(AppCompatDrawableManager.java:107)
        at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:85)
        at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:128)
        at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:149)
        at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:56)
        at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:202)
        at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183)
        at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
        at com.renyu.hjaocdemo.MainActivity.onCreate(MainActivity.kt:9)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)`

**Comment by w1sl1y** [comment]
我也是这个问题，头大

**Comment by lyanjun** [comment]
你们最后怎么解决的啊？

**Comment by r17171709** [comment]
@firefly1126 这个问题我在2.0.4上还是这样，后来该用2.0.0进行编译，编译完成之后再换2.0.4就没问题。是不是插件会检测文件如果已经存在就不会二次编译了？

**Comment by r17171709** [comment]
@lyanjun 没有解决，换成2.0.0了
