### ISSUE TITLE
include 标签对jar包及依赖的module无效

### ISSUE THREAD

**Issue by qsmaxmin** [HujiangTechnology/gradle_plugin_android_aspectjx#96]
集成友盟的push报的错误：
 java.lang.RuntimeException: Unable to get provider com.umeng.message.provider.MessageProvider: java.lang.ClassNotFoundException: Didn't find class "com.umeng.message.provider.MessageProvider" on path: DexPathList[[zip file "/data/app/com.font-Y8BElA2AAV3nu9I6s-w_9A==/base.apk"],nativeLibraryDirectories=[/data/app/com.font-Y8BElA2AAV3nu9I6s-w_9A==/lib/arm, /data/app/com.font-Y8BElA2AAV3nu9I6s-w_9A==/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /product/lib]]
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:7110)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6594)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6498)
                                                       at android.app.ActivityThread.-wrap2(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
                                                       at android.os.Handler.dispatchMessage(Handler.java:108)
                                                       at android.os.Looper.loop(Looper.java:166)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.umeng.message.provider.MessageProvider" on path: DexPathList[[zip file "/data/app/com.font-Y8BElA2AAV3nu9I6s-w_9A==/base.apk"],nativeLibraryDirectories=[/data/app/com.font-Y8BElA2AAV3nu9I6s-w_9A==/lib/arm, /data/app/com.font-Y8BElA2AAV3nu9I6s-w_9A==/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /product/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:7095)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6594) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6498) 
                                                       at android.app.ActivityThread.-wrap2(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:108) 
                                                       at android.os.Looper.loop(Looper.java:166) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7425) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 

好像跟ContentProvider有关，报的错是ClassNotFoundException

先试了exclude函数，将push项目忽略：
aspectjx {
    exclude 'com.umeng.message'
}
但错误仍然存在。

后来又试了下include函数
因为我这边项目依赖了一个框架，框架里有AOP代码，在项目里添加
aspectjx {
    include '项目包名'，‘框架包名’
}
但框架里的AOP不再生效！
亲问该怎么解决这个问题？

**Comment by qsmaxmin** [comment]
![image](https://user-images.githubusercontent.com/10693530/42090136-c04e8c5e-7bd2-11e8-9499-4438d35d71b3.png)
这是依赖的友盟push sdk，我查了下对应的build目录：
\app\build\intermediates\transforms\ajx
找到_content_.json文件找到push sdk对应的自动生成的jar包：
![image](https://user-images.githubusercontent.com/10693530/42090245-4f314204-7bd3-11e8-81cc-ce93e476f9e3.png)
复制43,44,45这三个jar包并解压：
其中44和45两个jar包里面对应的是图一httpdns和utils两个jar包的class文件。
而43里面仅有个META-INF目录，class文件并没有打包进来
所以一直报ClassNotFoundException
请知晓

**Comment by qsmaxmin** [comment]
后来我又试了下你这边的
demo（AspectJX-Demo：https://github.com/HujiangTechnology/AspectJX-Demo），在demo的app下的build.gradle里添：
aspectjx {
    include ‘com.android.library’
}
运行时也crash了，报的错误是方法找不到（这个方法是AOP自动生成的代码），也就是说include标签并不能很好的将library库编译成想要的结果，请知晓！

**Comment by qsmaxmin** [comment]
后来我又试了下你这边的AspectJX-Demo：
https://github.com/HujiangTechnology/AspectJX-Demo
在demo的app下的build.gradle里添：
aspectjx {
include ‘com.android.library’
}
运行时也crash了，报的错误是方法找不到（这个方法是AOP自动生成的代码），也就是说include标签并不能很好的将library库编译成想要的结果，请知晓！

**Comment by qsmaxmin** [comment]
后来我又试了下你这边的AspectJX-Demo：
https://github.com/HujiangTechnology/AspectJX-Demo
在demo的app下的build.gradle里添：
aspectjx {
include ‘com.hujiang.library’
}
运行时也crash了，报的错误是方法找不到（这个方法是AOP自动生成的代码），也就是说include标签并不能很好的将library库编译成想要的结果。
请知晓！

**Comment by qsmaxmin** [comment]
再后来我将版本回退到1.1.1
在demo的app下的build.gradle里添：
aspectjx {
    excludeJarFilter'push-4.2.0'
}
运行正常，也就是说2.0.1版本的exclude标签是有bug的，望修复，谢谢！

**Comment by enjoy008** [comment]
include 和 exclude 好像都没什么用，放在单独的module里是不行

**Comment by cxMax** [comment]
aspectjx {
    // fix Didn't find class "com.umeng.message.provider.MessageProvider" on path: DexPathList
    exclude 'com.umeng.message'
}

我增加了这句话， 对于我的项目有效

**Comment by tanghongbin** [comment]
真是aspectJ引起的，感谢这位老兄，排查一会儿不知问题所在，看来以后还是尽量少导依赖注入框架，不小心就掉坑里了
